version: "3.1"

services:
  db:
    container_name: my_database
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  #   volumes:
  #     - db:/var/lib/postgresql/data

  # volumes:
  # db:
  #   driver: local

  # api:
  #   container_name: backend
  #   build: "./backend"
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  # client:
  #   build: "./frontend"
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - api
